num1=float(input("digite o primeiro número: "))
num2=float(input("digite o segundo número: "))
print("soma:",num1+num2)
print("subtração:,num1-num2")
print("multiplicação:",num1*num2)
print("divisão:",num1/num2)
